#!/usr/bin/env bash
# Shared BPSTracker installer environment helpers.
# This file is meant to be sourced by deploy scripts.

bpstracker_generate_hex() {
  local bytes="${1:-32}"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  elif command -v python3 >/dev/null 2>&1; then
    python3 - <<PY
import secrets
print(secrets.token_hex($bytes))
PY
  else
    echo "ERROR: openssl or python3 is required to generate secure secrets." >&2
    return 1
  fi
}


bpstracker_normalize_language() {
  case "${1:-}" in
    en|EN|english|English|2) printf 'en\n' ;;
    de|DE|german|German|deutsch|Deutsch|1|'') printf 'de\n' ;;
    *) printf 'de\n' ;;
  esac
}

bpstracker_is_english() {
  [ "${BPSTRACKER_LANGUAGE:-de}" = "en" ]
}

bpstracker_env_language_or_empty() {
  local file="${1:-}"
  local value=""
  if [ -n "${BPSTRACKER_LANGUAGE:-}" ]; then
    value="$BPSTRACKER_LANGUAGE"
  elif [ -n "$file" ] && [ -f "$file" ]; then
    value="$(bpstracker_env_get "$file" BPSTRACKER_LANGUAGE || true)"
    [ -n "$value" ] || value="$(bpstracker_env_get "$file" BPSTRACKER_DEFAULT_LANGUAGE || true)"
  fi
  case "$value" in
    de|en) printf '%s\n' "$value" ;;
  esac
}

bpstracker_select_language() {
  local env_file="${1:-}"
  local existing=""
  existing="$(bpstracker_env_language_or_empty "$env_file" || true)"

  if [ ! -t 0 ]; then
    if [ -n "$existing" ]; then
      printf '%s\n' "$existing"
      return 0
    fi
    case "${LANG:-}" in
      de_*|de.*|de) printf 'de\n' ;;
      *) printf 'en\n' ;;
    esac
    return 0
  fi

  echo ""
  echo "Sprache / Language"
  echo "  1) Deutsch"
  echo "  2) English"
  if [ "$existing" = "en" ]; then
    printf 'Auswahl / Selection [1/2, Standard/default: 2]: '
  else
    printf 'Auswahl / Selection [1/2, Standard/default: 1]: '
  fi
  local choice
  read -r choice || choice=""
  if [ -z "$choice" ] && [ -n "$existing" ]; then
    printf '%s\n' "$existing"
  else
    bpstracker_normalize_language "$choice"
  fi
}

bpstracker_profile_label() {
  if [ "${1:-}" = "zero2w" ]; then
    if bpstracker_is_english; then printf 'Raspberry Pi Zero 2 W / low-resource installation\n'; else printf 'Raspberry Pi Zero 2 W / Low-Resource-Installation\n'; fi
  else
    if bpstracker_is_english; then printf 'regular installation\n'; else printf 'reguläre Installation\n'; fi
  fi
}

bpstracker_env_get() {
  local file="$1"
  local key="$2"
  if [ -f "$file" ]; then
    grep -E "^${key}=" "$file" 2>/dev/null | tail -n1 | cut -d= -f2- || true
  fi
}

bpstracker_env_set() {
  local file="$1"
  local key="$2"
  local value="$3"
  local tmp
  tmp="$(mktemp)"
  if [ -f "$file" ] && grep -qE "^${key}=" "$file"; then
    awk -v key="$key" -v value="$value" 'BEGIN{done=0} $0 ~ "^" key "=" {print key "=" value; done=1; next} {print} END{if(!done) print key "=" value}' "$file" > "$tmp"
  else
    if [ -f "$file" ]; then
      cat "$file" > "$tmp"
      printf '\n%s=%s\n' "$key" "$value" >> "$tmp"
    else
      printf '%s=%s\n' "$key" "$value" > "$tmp"
    fi
  fi
  mv "$tmp" "$file"
}

bpstracker_is_unsafe_secret() {
  local value="$1"
  [ -z "$value" ] && return 0
  case "$value" in
    change-me*|changeme*|please-change*|secret|default|example) return 0 ;;
  esac
  [ "${#value}" -lt 32 ] && return 0
  return 1
}

bpstracker_is_unsafe_pg_password() {
  local value="$1"
  [ -z "$value" ] && return 0
  case "$value" in
    change-me*|changeme*|password|postgres|bpstracker|example) return 0 ;;
  esac
  [ "${#value}" -lt 16 ] && return 0
  return 1
}

bpstracker_select_profile() {
  local current="${BPSTRACKER_INSTALL_PROFILE:-}"
  if [ "$current" = "regular" ] || [ "$current" = "zero2w" ]; then
    printf '%s\n' "$current"
    return 0
  fi

  if [ ! -t 0 ]; then
    printf 'regular\n'
    return 0
  fi

  echo ""
  if bpstracker_is_english; then
    echo "Which installation profile do you want to use?"
    echo "  1) Regular installation"
    echo "  2) Raspberry Pi Zero 2 W / low-resource installation"
    printf 'Selection [1/2, default: 1]: '
  else
    echo "Welche Installation möchtest du verwenden?"
    echo "  1) Reguläre Installation"
    echo "  2) Raspberry Pi Zero 2 W / Low-Resource-Installation"
    printf 'Auswahl [1/2, Standard: 1]: '
  fi
  local choice
  read -r choice || choice=""
  case "$choice" in
    2|z|Z|zero|zero2w|Zero2W) printf 'zero2w\n' ;;
    *) printf 'regular\n' ;;
  esac
}

bpstracker_write_new_env() {
  local env_file="$1"
  local profile="$2"
  local secret_key="$3"
  local pg_password="$4"
  local image_tag="$5"
  local language="${6:-de}"
  language="$(bpstracker_normalize_language "$language")"
  local pi_mode="false"
  local live_hours="0"
  local raw_hours="0"
  local polling="5"
  local timeout="5"
  local concurrency="4"

  if [ "$profile" = "zero2w" ]; then
    pi_mode="true"
    live_hours="24"
    raw_hours="24"
    polling="10"
    timeout="4"
    concurrency="1"
  fi

  cat > "$env_file" <<EOF_ENV
# BPSTracker runtime configuration
# Generated by the BPSTracker install script. Do not copy .env.example for production use.

APP_NAME=BPSTracker

POSTGRES_DB=bpstracker
POSTGRES_USER=bpstracker
POSTGRES_PASSWORD=$pg_password
DATABASE_URL=postgresql+psycopg://bpstracker:$pg_password@postgres:5432/bpstracker

FRONTEND_PORT=5173
VITE_API_BASE_URL=same-origin
BPSTRACKER_IMAGE_TAG=$image_tag
BPSTRACKER_LANGUAGE=$language
BPSTRACKER_DEFAULT_LANGUAGE=$language

# Do not change after production start: it encrypts Shelly passwords and Admin 2FA secrets.
SECRET_KEY=$secret_key
ACCESS_TOKEN_EXPIRE_MINUTES=720
AUTH_COOKIE_NAME=bpstracker_access_token
AUTH_COOKIE_SECURE=false
AUTH_COOKIE_SAMESITE=lax
FRONTEND_ORIGIN=*

POLLING_LOOP_SECONDS=$polling
SHELLY_TIMEOUT_SECONDS=$timeout
SHELLY_MAX_CONCURRENCY=$concurrency

BPSTRACKER_INSTALL_PROFILE=$profile
PI_ZERO_2W_MODE=$pi_mode
LIVE_DATA_MAX_HOURS=$live_hours
RAW_RETENTION_HOURS=$raw_hours

# Optional: override regeneratable Kindle PNG cache path. Default: /tmp/bpstracker-kindle-display.png
# KINDLE_OUTPUT_PATH=/tmp/bpstracker-kindle-display.png
EOF_ENV
  chmod 600 "$env_file" 2>/dev/null || true
}

bpstracker_prepare_env() {
  local env_file="$1"
  local profile="$2"
  local image_tag="${3:-v0.9.15}"
  local language="${4:-${BPSTRACKER_LANGUAGE:-de}}"
  language="$(bpstracker_normalize_language "$language")"
  local generated_secret=""
  local generated_pg=""
  local created="false"

  mkdir -p "$(dirname "$env_file")"

  if [ ! -f "$env_file" ]; then
    generated_secret="$(bpstracker_generate_hex 32)"
    generated_pg="$(bpstracker_generate_hex 24)"
    bpstracker_write_new_env "$env_file" "$profile" "$generated_secret" "$generated_pg" "$image_tag" "$language"
    created="true"
  else
    local secret_key pg_password db_name db_user db_url
    secret_key="$(bpstracker_env_get "$env_file" SECRET_KEY)"
    pg_password="$(bpstracker_env_get "$env_file" POSTGRES_PASSWORD)"
    db_name="$(bpstracker_env_get "$env_file" POSTGRES_DB)"
    db_user="$(bpstracker_env_get "$env_file" POSTGRES_USER)"
    db_name="${db_name:-bpstracker}"
    db_user="${db_user:-bpstracker}"

    bpstracker_env_set "$env_file" APP_NAME "$(bpstracker_env_get "$env_file" APP_NAME || true)"
    [ -n "$(bpstracker_env_get "$env_file" APP_NAME)" ] || bpstracker_env_set "$env_file" APP_NAME "BPSTracker"
    bpstracker_env_set "$env_file" POSTGRES_DB "$db_name"
    bpstracker_env_set "$env_file" POSTGRES_USER "$db_user"

    if bpstracker_is_unsafe_pg_password "$pg_password"; then
      pg_password="$(bpstracker_generate_hex 24)"
      generated_pg="$pg_password"
      bpstracker_env_set "$env_file" POSTGRES_PASSWORD "$pg_password"
    fi

    db_url="$(bpstracker_env_get "$env_file" DATABASE_URL)"
    if [ -z "$db_url" ] || echo "$db_url" | grep -Eq 'change-me|changeme|password'; then
      bpstracker_env_set "$env_file" DATABASE_URL "postgresql+psycopg://${db_user}:${pg_password}@postgres:5432/${db_name}"
    fi

    if bpstracker_is_unsafe_secret "$secret_key"; then
      secret_key="$(bpstracker_generate_hex 32)"
      generated_secret="$secret_key"
      bpstracker_env_set "$env_file" SECRET_KEY "$secret_key"
    fi

    [ -n "$(bpstracker_env_get "$env_file" FRONTEND_PORT)" ] || bpstracker_env_set "$env_file" FRONTEND_PORT "5173"
    [ -n "$(bpstracker_env_get "$env_file" VITE_API_BASE_URL)" ] || bpstracker_env_set "$env_file" VITE_API_BASE_URL "same-origin"
    [ -n "$(bpstracker_env_get "$env_file" BPSTRACKER_IMAGE_TAG)" ] || bpstracker_env_set "$env_file" BPSTRACKER_IMAGE_TAG "$image_tag"
    bpstracker_env_set "$env_file" BPSTRACKER_LANGUAGE "$language"
    bpstracker_env_set "$env_file" BPSTRACKER_DEFAULT_LANGUAGE "$language"
    [ -n "$(bpstracker_env_get "$env_file" ACCESS_TOKEN_EXPIRE_MINUTES)" ] || bpstracker_env_set "$env_file" ACCESS_TOKEN_EXPIRE_MINUTES "720"
    [ -n "$(bpstracker_env_get "$env_file" AUTH_COOKIE_NAME)" ] || bpstracker_env_set "$env_file" AUTH_COOKIE_NAME "bpstracker_access_token"
    [ -n "$(bpstracker_env_get "$env_file" AUTH_COOKIE_SECURE)" ] || bpstracker_env_set "$env_file" AUTH_COOKIE_SECURE "false"
    [ -n "$(bpstracker_env_get "$env_file" AUTH_COOKIE_SAMESITE)" ] || bpstracker_env_set "$env_file" AUTH_COOKIE_SAMESITE "lax"
    [ -n "$(bpstracker_env_get "$env_file" FRONTEND_ORIGIN)" ] || bpstracker_env_set "$env_file" FRONTEND_ORIGIN "*"
    [ -n "$(bpstracker_env_get "$env_file" POLLING_LOOP_SECONDS)" ] || bpstracker_env_set "$env_file" POLLING_LOOP_SECONDS "5"
    [ -n "$(bpstracker_env_get "$env_file" SHELLY_TIMEOUT_SECONDS)" ] || bpstracker_env_set "$env_file" SHELLY_TIMEOUT_SECONDS "5"
    [ -n "$(bpstracker_env_get "$env_file" SHELLY_MAX_CONCURRENCY)" ] || bpstracker_env_set "$env_file" SHELLY_MAX_CONCURRENCY "4"

    bpstracker_env_set "$env_file" BPSTRACKER_INSTALL_PROFILE "$profile"
    if [ "$profile" = "zero2w" ]; then
      bpstracker_env_set "$env_file" PI_ZERO_2W_MODE "true"
      bpstracker_env_set "$env_file" LIVE_DATA_MAX_HOURS "24"
      bpstracker_env_set "$env_file" RAW_RETENTION_HOURS "24"
      bpstracker_env_set "$env_file" POLLING_LOOP_SECONDS "10"
      bpstracker_env_set "$env_file" SHELLY_TIMEOUT_SECONDS "4"
      bpstracker_env_set "$env_file" SHELLY_MAX_CONCURRENCY "1"
    else
      [ -n "$(bpstracker_env_get "$env_file" PI_ZERO_2W_MODE)" ] || bpstracker_env_set "$env_file" PI_ZERO_2W_MODE "false"
      [ -n "$(bpstracker_env_get "$env_file" LIVE_DATA_MAX_HOURS)" ] || bpstracker_env_set "$env_file" LIVE_DATA_MAX_HOURS "0"
      [ -n "$(bpstracker_env_get "$env_file" RAW_RETENTION_HOURS)" ] || bpstracker_env_set "$env_file" RAW_RETENTION_HOURS "0"
    fi
    chmod 600 "$env_file" 2>/dev/null || true
  fi

  local final_secret final_pg final_db_url
  final_secret="$(bpstracker_env_get "$env_file" SECRET_KEY)"
  final_pg="$(bpstracker_env_get "$env_file" POSTGRES_PASSWORD)"
  final_db_url="$(bpstracker_env_get "$env_file" DATABASE_URL)"

  if bpstracker_is_unsafe_secret "$final_secret"; then
    echo "ERROR: SECRET_KEY in $env_file is missing or unsafe." >&2
    return 1
  fi
  if bpstracker_is_unsafe_pg_password "$final_pg"; then
    echo "ERROR: POSTGRES_PASSWORD in $env_file is missing or unsafe." >&2
    return 1
  fi
  if [ -z "$final_db_url" ] || echo "$final_db_url" | grep -Eq 'change-me|changeme'; then
    echo "ERROR: DATABASE_URL in $env_file is missing or unsafe." >&2
    return 1
  fi

  echo ""
  if bpstracker_is_english; then
    if [ "$created" = "true" ]; then
      echo "Created $env_file from generated secure values. .env.example was not copied."
    else
      echo "Checked $env_file and replaced missing/unsafe generated values if needed. .env.example was not copied."
    fi
  else
    if [ "$created" = "true" ]; then
      echo "$env_file wurde aus sicheren Zufallswerten erzeugt. .env.example wurde nicht kopiert."
    else
      echo "$env_file wurde geprüft; fehlende/unsichere Werte wurden bei Bedarf ersetzt. .env.example wurde nicht kopiert."
    fi
  fi

  if [ -n "$generated_secret" ]; then
    echo ""
    if bpstracker_is_english; then
      echo "Generated SECRET_KEY. Store this value safely and do not change it after production start:"
    else
      echo "SECRET_KEY wurde erzeugt. Bitte sicher aufbewahren und nach Produktivstart nicht mehr ändern:"
    fi
    echo "$generated_secret"
  fi
  if [ -n "$generated_pg" ]; then
    if bpstracker_is_english; then
      echo "Generated a secure POSTGRES_PASSWORD and matching DATABASE_URL."
    else
      echo "Sicheres POSTGRES_PASSWORD und passende DATABASE_URL wurden erzeugt."
    fi
  fi
}

bpstracker_compose_file_for_profile() {
  local profile="$1"
  local deployment_kind="${2:-local}"
  if [ "$profile" = "zero2w" ]; then
    printf 'docker-compose.zero2w.yml\n'
  elif [ "$deployment_kind" = "images" ]; then
    printf 'docker-compose.images.yml\n'
  else
    printf 'docker-compose.yml\n'
  fi
}
